version: '3'
services:
    database:
        build:
            context: .
            dockerfile: Dockerfile-db
        image: usgs/hazdev-geoserve-db:latest
        environment:
            - DATALOAD_DIR=/tmp/dataload
            - DB_ADMIN_USER=postgres
            - DB_ADMIN_PASSWORD=postgres
            - DB_LOAD_TYPE=incremental
            - DB_NAME=earthquake
            - DB_SCHEMA=geoserve
            - DB_ADMIN_DSN=pgsql:dbname=earthquake
            - PGDATA=/var/lib/postgresqsl/data/pgdata
            - POSTGRES_PASSWORD=postgres
        # volumes:
        # volume to store downloaded data files
        #    - ./data/dataload:/tmp/dataload
        # volume to store database data files
        #    - ./data/pgdata:/var/lib/postgresqsl/data/pgdata
    web:
        build:
            context: .
            dockerfile: Dockerfile-ws
        image: usgs/hazdev-geoserve-ws:latest
        links:
            - database
        environment:
            - DB_DSN=pgsql:host=database;port=5432;dbname=earthquake
            - DB_USER=postgres
            - DB_PASS=postgres
            - DB_SCHEMA=geoserve
        volumes:
            # volumes for local dev
            - ./src/htdocs:/var/www/apps/hazdev-geoserve-ws/htdocs
            - ./src/lib:/var/www/apps/hazdev-geoserve-ws/lib
        ports:
            - "8080:80"